name: Build Develop Images

on:
  push:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/pytest.yml

  build:
    name: build and deploy dev images
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: clone ocs
      uses: actions/checkout@v2
      # Fetch all history for all tags and branches
      with:
        fetch-depth: 0

    # Dockerize
    - name: Build all docker images
      run: |
        docker-compose build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push development docker image
      env:
        DOCKERHUB_ORG: "simonsobs"
      run: |
        export DOCKER_TAG=`git describe --tags --always`-dev
        echo "${DOCKER_TAG}"

        # Tag all images for upload to the registry
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker tag {}:latest ${DOCKERHUB_ORG}/{}:${DOCKER_TAG}

        # Upload to docker registry
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} docker push ${DOCKERHUB_ORG}/{}:${DOCKER_TAG}
        docker-compose config | grep 'image: ' | awk -F ': ' '{ print $2 }' | xargs -I {} echo ${DOCKERHUB_ORG}/{}:${DOCKER_TAG} pushed
