# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches-ignore: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: clone ocs
      uses: actions/checkout@v2

    # I like this idea, but let's hold off for now.
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install ocs
      run: |
        pip3 install -r requirements.txt
        pip3 install -e .

    # Unit Tests
    - name: Run unit tests
      working-directory: ./tests
      run: |
        COVERAGE_FILE=.coverage.unit python3 -m pytest --cov -m 'not (integtest or spt3g)'

    - name: Build docker images
      run: |
        docker-compose build

    - name: Test with pytest within a docker container
      run: |
        docker run -v $PWD:/coverage --rm -w="/app/ocs/tests/" ocs sh -c "COVERAGE_FILE=/coverage/.coverage.docker python3 -m pytest --cov -m 'spt3g'"

    - name: Report test coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv ./tests/.coverage.* ./
        pip install coveralls
        coverage combine
        coverage report
        coveralls --service=github

    - name: Test documentation build
      run: |
        docker run --rm ocs sh -c "make -C docs/ html"
